# ./docker-compose.yml

version: '3.7'

services:
  postgres:
    image: postgres:11.3-alpine
    container_name: help_proj_postgres
    restart: always
    ports: 
      - "15432:5432"
    
        
